services:
  web:
    container_name: web
    build: .
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    working_dir: /var/www/html
    links: 
      - db
    ports:
      - 80:80
  db:
    image: mysql
    container_name: mysqldb
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: clothingshop
    ports:
      - 3306:3306